---
- name: test listner
  hosts: localhost
  sources:
   - name: api_listener
     type: ansible.eda.webhook
     config:
      hosts: 0.0.0.0
      port: 5003

  rules:
    - name: Run Job Template
      condition: event.payload.action == "run_job"
      action:
        run_job_template:
          name: first_template
          organization: testorg
