---
- name: test listner
  hosts: localhost
  sources:
   - name: api_listener
     type: ansible.eda.webhook
     config:
      hosts: 0.0.0.0
      port: 5003

  rules:
    - name: Run Job Template
      condition: event.payload.sr_number is defined
      action:
        run_job_template:
          name: "Fetch_SR_Details_SG"
          organization: Prudential
          job_args:
            execution_mode: "asynchronous"
            extra_vars:
              sr_number: "{{ event.payload.sr_number }}"

